portfolio_data = {
    "profile": {
        "name": "박주원",
        "role": "Backend & Web Developer",
        "email": "ehdrbs8751@naver.com",
        "github": "https://github.com/Zwonnyy",
        "summary": "웹 서비스 개발과 백엔드 구현을 중심으로 성장하고 있는 개발자입니다. 대학정보시스템 개발 및 사업관리 경험을 통해 실제 사용자의 요구사항을 기능으로 구현하는 과정을 경험했습니다.",
        "focus": "Java, Spring, JSP, SQL 기반의 웹 개발 경험을 바탕으로 안정적인 서비스 구조와 사용자 흐름을 고민합니다.",
    },
    "quickProfile": [
        {"label": "지원 직무", "value": "Backend Developer / Web Developer"},
        {"label": "주요 기술", "value": "Java, Spring, JSP, Servlet, MyBatis, SQL"},
        {"label": "실무 경험", "value": "대학정보시스템 개발 및 사업관리"},
        {"label": "강점", "value": "요구사항 이해, 기능 구현, 문제 해결, 커뮤니케이션"},
    ],
    "about": {
        "title": "사용자의 요구사항을 기능으로 구현하는 개발자",
        "paragraphs": [
            "저는 사용자의 요구사항을 이해하고, 이를 실제 기능으로 구현하는 과정에 흥미를 느낍니다. 개발 업무를 수행하면서 단순히 화면을 만드는 것보다, 사용자가 어떤 흐름으로 서비스를 이용하는지, 어떤 부분에서 불편함을 느끼는지를 함께 고민하는 것이 중요하다고 느꼈습니다.",
            "현재는 Java와 Spring 기반 백엔드 개발 역량을 중심으로, 웹 서비스 구조와 데이터베이스 연동, API 설계 역량을 꾸준히 확장하고 있습니다.",
        ],
        "strengths": [
            "요구사항 이해와 기능 단위 정리",
            "개발 및 사업관리 경험 기반 커뮤니케이션",
            "문제 원인 분석과 해결 중심의 태도",
        ],
    },
    "career": {
        "company": "(주)위지언",
        "role": "차세대 대학정보시스템 개발",
        "period": "2023.07 ~ 2024.12",
        "team": "개발팀 소속",
        "description": "개발팀 소속으로 대학정보시스템 개발 및 사업관리 업무를 수행했습니다. 주로 프론트엔드 개발 업무를 담당했으며, 사용자 요구사항을 확인하고 기능 개선 방향을 정리하는 업무도 함께 진행했습니다.",
        "tasks": [
            "대학정보시스템 화면 개발 및 유지보수",
            "사용자 요구사항 확인 및 기능 개선 정리",
            "일정 관리 지원 및 문서 정리",
        ],
        "stack": ["Java", "JSP", "Servlet", "Spring", "MyBatis", "Oracle", "Nexacro", "Git"],
        "learning": "요구사항을 기능 단위로 정리하고 개발 방향으로 연결하는 경험을 쌓았으며, 개발 업무와 사업관리 업무를 함께 수행하며 커뮤니케이션의 중요성을 배웠습니다.",
    },
    "projects": [
        {
            "title": "FootMap",
            "type": "Team Project",
            "period": "2022.09 ~ 2022.11",
            "role": "Frontend / Backend 담당 역할 입력",
            "description": "지역 기반 풋살 매칭을 도와주는 웹 서비스입니다. 사용자가 풋살팀 정보를 확인하고, 조건에 맞는 팀 또는 매칭 정보를 쉽게 탐색할 수 있도록 구성했습니다.",
            "stack": ["Java", "Spring", "JSP", "Oracle", "MyBatis", "JavaScript", "HTML", "CSS"],
            "features": ["풋살팀 정보 조회", "지역 및 조건 기반 매칭 탐색", "매칭 정보 확인", "사용자 중심 화면 구성", "팀 프로젝트 발표 자료 구성"],
            "contributions": ["메인 화면 및 주요 UI 구성", "풋살팀 목록 화면 구현", "사용자 조건에 따른 데이터 출력 구조 정리", "화면 흐름과 사용자 동선 설계", "프로젝트 기능 설명 및 발표 자료 정리"],
            "problem": "풋살 매칭 정보가 한눈에 보이지 않으면 사용자가 원하는 팀이나 매칭 조건을 찾기 어렵다고 판단했습니다. 주요 정보를 카드 형태로 정리하고, 목록과 상세 영역을 구분해 사용자가 빠르게 정보를 탐색할 수 있도록 구성했습니다.",
            "github": "https://github.com/Zwonnyy/footmap",
        },
        {
            "title": "이슈 관리 REST API",
            "type": "Backend Project",
            "period": "2025.07",
            "role": "Backend Developer",
            "description": "Go와 Gin 프레임워크를 활용해 이슈 생성, 조회, 수정, 상태 변경 기능을 구현한 RESTful API 프로젝트입니다. 담당자 지정 여부에 따른 상태 처리와 에러 응답 구조를 설계했습니다.",
            "stack": ["Go", "Gin", "REST API", "JSON", "Memory Store"],
            "features": ["이슈 생성 API", "이슈 목록 및 상세 조회 API", "상태값 기반 이슈 필터링", "이슈 수정 및 담당자 변경", "JSON 기반 에러 응답 처리"],
            "contributions": ["Go 구조체 기반 User, Issue 모델 설계", "Gin Router를 활용한 REST API 엔드포인트 구성", "PENDING, IN_PROGRESS, COMPLETED, CANCELLED 상태 흐름 설계", "잘못된 요청에 대한 공통 에러 응답 형식 정리", "컨트롤러, 라우터, 모델, 데이터 계층을 분리하여 프로젝트 구조화"],
            "problem": "단순 CRUD에 그치지 않고 담당자 지정 여부와 이슈 상태에 따라 처리 흐름이 달라지도록 구현했습니다. 완료 또는 취소된 이슈는 수정이 불가능하도록 제한해 실제 업무 관리 API에 가까운 비즈니스 규칙을 반영했습니다.",
            "github": "https://github.com/Zwonnyy/Issue_api",
        },
        {
            "title": "Django Review 서비스",
            "type": "Web Backend Project",
            "period": "2025.08",
            "role": "Backend / Full-stack Developer",
            "description": "Django 기반으로 사용자, 음식점, 리뷰 도메인을 분리해 구성한 리뷰 서비스 프로젝트입니다. Django의 앱 구조를 활용해 기능별 책임을 나누고, 리뷰 데이터를 관리하는 웹 서비스 구조를 학습했습니다.",
            "stack": ["Python", "Django", "SQLite", "HTML", "CSS"],
            "features": ["사용자 앱 구조 구성", "음식점 정보 관리 구조 구성", "리뷰 작성 및 관리 구조 구성", "Django 프로젝트 설정 및 앱 분리"],
            "contributions": ["config, users, restaurants, reviews 앱 구조 분리", "Django 프로젝트 기본 설정 및 실행 구조 구성", "리뷰 서비스에 필요한 도메인 단위 폴더 구조 설계", "Django MTV 패턴을 기반으로 서비스 구조 정리"],
            "problem": "초기에는 기능을 한곳에 모아 관리하기 쉬웠지만, 기능이 늘어날수록 유지보수가 어려워질 수 있다고 판단했습니다. 사용자, 음식점, 리뷰 기능을 앱 단위로 분리해 각 기능의 책임을 명확히 나누는 방향으로 구조를 잡았습니다.",
            "github": "https://github.com/Zwonnyy/Django-Review",
        },
    ],
    "skills": {
        "main": ["Java", "Spring / Spring Boot", "JSP / Servlet", "MyBatis", "Oracle / MySQL", "SQL"],
        "sub": ["Python", "Django", "Flask", "FastAPI", "JavaScript", "HTML / CSS", "jQuery","Go"],
        "tools": ["Git / GitHub", "IntelliJ", "Eclipse", "VS Code", "PyCharm", "Toad", "Nexacro"],
        "details": [
            {"title": "Java / Spring", "items": ["Spring MVC 기반 웹 서비스 구조를 이해하고 있습니다.", "JSP, Servlet, MyBatis를 활용한 화면 및 데이터 연동 경험이 있습니다.", "실제 업무에서 대학정보시스템 개발 및 유지보수 흐름을 경험했습니다."]},
            {"title": "Frontend", "items": ["HTML, CSS, JavaScript, jQuery를 활용하여 웹 화면을 구현할 수 있습니다.", "사용자 화면 흐름과 기본적인 UI 구성을 고려하여 개발합니다.", "Nexacro 기반 화면 개발 경험이 있습니다."]},
            {"title": "Database", "items": ["Oracle, MySQL 기반 데이터 조회 및 기본적인 SQL 작성 경험이 있습니다.", "화면에서 필요한 데이터를 조회하고 출력하는 흐름을 이해하고 있습니다.", "MyBatis를 활용한 데이터 연동 경험이 있습니다."]},
        ],
    },
    "education": [
        {"name": "Oz Coding School", "course": "넥스트러러스 초격차 교육 - 백엔드 과정", "period": "2025.05 ~ 2025.11", "details": ["K-Digital Training 과정 수료", "Java / Spring 기반 백엔드 개발 학습", "데이터베이스 및 SQL 활용", "REST API 및 서버 구조 학습"]},
        {"name": "국비지원교육", "course": "머신러닝 SW 개발자 과정", "period": "2022.07 ~ 2023.02", "details": ["Python 프로그래밍 학습", "데이터 분석 및 시각화", "머신러닝 기초 학습", "팀 프로젝트 수행"]},
        {"name": "경성대학교", "course": "생물학", "period": "2013.03 ~ 2019.02"},
    ],
}
